---
name: 'deploy'

on:
  push:
    branches:
      - main

concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Cloning repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push to dokku
        uses: dokku/github-action@cc7dec1d2b9fed249a14ae462bc953bba436f78c
        with:
          branch: main
          git_remote_url: 'ssh://dokku@${{ secrets.SERVER_IP }}:${{ secrets.SSH_PORT }}/home'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
